### ISSUE TITLE
Chapters in example.py are fetched twice

### ISSUE THREAD

**Issue by vessd** [Ae-Mc/AuthorTodayToFB2Converter#7]
First:
https://github.com/Ae-Mc/AuthorTodayToFB2Converter/blob/f3d67856420eb27b00e57fbc4d7e72dbfc790e0f/example.py#L23
https://github.com/Ae-Mc/AuthorTodayToFB2Converter/blob/f3d67856420eb27b00e57fbc4d7e72dbfc790e0f/Classes/Book.py#L24

Second:
https://github.com/Ae-Mc/AuthorTodayToFB2Converter/blob/f3d67856420eb27b00e57fbc4d7e72dbfc790e0f/example.py#L43

**Comment by Ae-Mc** [comment]
Fixed

**Comment by vessd** [comment]
@Ae-Mc Either you didn't upload the changes, or the problem is not fixed.
